# Checks for uncommitted changes to built files in pull requests.
name: Check Built Files (PRs)

on:
  # Because all commits happen through SVN and should always be manually reviewed by a committer, this workflow only
  # runs for pull requests.
  #
  # Other workflows that run for the push event will detect changes to versioned files and fail.
  pull_request:
    branches:
      - trunk
      - '6.[8-9]'
      - '[7-9].[0-9]'
    paths:
      # Any change to a CSS, JavaScript, JSON, or SASS file should run checks.
      - '**.css'
      - '**.js'
      - '**.json'
      - '**.sass'
      # These files configure npm and the task runner. Changes could affect the outcome.
      - 'package*.json'
      - '.npmrc'
      - '.nvmrc'
      - 'Gruntfile.js'
      - 'webpack.config.js'
      - 'tools/webpack/**'
      # These files configure Composer. Changes could affect the outcome.
      - 'composer.*'
      # Confirm any changes to relevant workflow files.
      - '.github/workflows/check-built-files.yml'
      # Changes to the default themes should be handled by the themes workflows.
      - '!src/wp-content/themes/twenty**'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  check-for-built-file-changes:
    name: Check built files
    if: ${{ github.repository == 'wordpress/wordpress-develop' }}
    uses: ./.github/workflows/reusable-check-built-files.yml
    permissions:
      contents: read
