# A reusable workflow that runs WordPress upgrade testing under the conditions provided.
name: Upgrade Tests

on:
  workflow_call:
    inputs:
      os:
        description: 'Operating system to run tests on.'
        required: false
        type: 'string'
        default: 'ubuntu-24.04'
      wp:
        description: 'The version of WordPress to start with.'
        required: true
        type: 'string'
      new-version:
        description: 'The version of WordPress to update to. Use "latest" to update to the latest version, "develop" to update to the current branch, or provide a specific version number to update to.'
        type: 'string'
        default: 'latest'
      php:
        description: 'The version of PHP to use. Expected format: X.Y.'
        required: true
        type: 'string'
      multisite:
        description: 'Whether to run tests as multisite.'
        required: false
        type: 'boolean'
        default: false
      db-type:
        description: 'Database type. Valid types are mysql and mariadb.'
        required: false
        type: 'string'
        default: 'mysql'
      db-version:
        description: 'Database version.'
        required: false
        type: 'string'
        default: '5.7'

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  # Runs upgrade tests on a build of WordPress.
  #
  # Performs the following steps:
  # - Sets up PHP.
  # - Downloads the specified version of WordPress.
  # - Creates a `wp-config.php` file.
  # - Installs WordPress.
  # - Checks the version of WordPress before the upgrade.
  # - Updates to the latest minor version.
  # - Updates the database after the minor update.
  # - Checks the version of WordPress after the minor update.
  # - Updates to the version of WordPress being tested.
  # - Updates the database.
  # - Checks the version of WordPress after the upgrade.
  upgrade-tests:
    name: PHP ${{ inputs.php }} with ${{ 'mariadb' == inputs.db-type && 'MariaDB' || 'MySQL' }} ${{ inputs.db-version }}${{ inputs.multisite && ' multisite' || '' }}
    permissions:
      contents: read
    runs-on: ${{ inputs.os }}
    timeout-minutes: 20

    services:
      database:
        image: ${{ inputs.db-type }}:${{ inputs.db-version }}
        ports:
          - 3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval="30s"
          --health-timeout="10s"
          --health-retries="5"
          -e MYSQL_ROOT_PASSWORD="root"
          -e MYSQL_DATABASE="test_db"
          --entrypoint sh ${{ inputs.db-type }}:${{ inputs.db-version }}
          -c "exec docker-entrypoint.sh mysqld${{ inputs.db-type == 'mysql' && contains( fromJSON('["7.2", "7.3"]'), inputs.php ) && ' --default-authentication-plugin=mysql_native_password' || '' }}"

    steps:
      - name: Set up PHP ${{ inputs.php }}
        uses: shivammathur/setup-php@bf6b4fbd49ca58e4608c9c89fba0b8d90bd2a39f # v2.35.5
        with:
          php-version: '${{ inputs.php }}'
          coverage: none
          tools: wp-cli

      - name: Download WordPress ${{ inputs.wp }}
        run: wp core download --version="${WP_VERSION}"
        env:
          WP_VERSION: ${{ inputs.wp }}

      - name: Create wp-config.php file
        run: wp config create --dbname=test_db --dbuser=root --dbpass=root --dbhost="127.0.0.1:${DB_PORT}"
        env:
          DB_PORT: ${{ job.services.database.ports['3306'] }}

      - name: Install WordPress
        run: |
          wp core ${{ inputs.multisite && 'multisite-install' || 'install' }} \
          --url=http://localhost/ --title="Upgrade Test" --admin_user=admin \
          --admin_password=password --admin_email=me@example.org --skip-email

      - name: Pre-upgrade version check
        run: wp core version

      - name: Update to the latest minor version
        run: wp core update --minor

      - name: Update the database after the minor update
        run: wp core update-db ${{ inputs.multisite && '--network' || '' }}

      - name: Post-upgrade version check after the minor update
        run: wp core version

      - name: Download build artifact for the current branch
        if: ${{ inputs.new-version == 'develop' }}
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: wordpress-develop

      - name: Upgrade to WordPress at current branch
        if: ${{ inputs.new-version == 'develop' }}
        run: |
          wp core update develop.zip

      - name: Upgrade to WordPress ${{ inputs.new-version }}
        if: ${{ inputs.new-version != 'develop' }}
        run: |
          wp core update ${{ 'latest' != inputs.new-version && '--version="${WP_VERSION}"' || '' }}
        env:
          WP_VERSION: ${{ inputs.new-version }}

      - name: Update the database
        run: wp core update-db ${{ inputs.multisite && '--network' || '' }}

      - name: Post-upgrade version check
        run: wp core version
